"""Tests that catch documentation-vs-code drift.

Documentation accumulates stale references over time: command names
get renamed, flags get removed, file paths get reorganized. These
tests programmatically verify that:

  1. Every CLI command name mentioned in user-facing markdown
     (`README.md`, `BENCHMARK.md`, `paper/README.md`,
     `data/synthea/README.md`) actually exists in the typer app.
  2. Every project-relative file path mentioned in those docs
     actually exists on disk.

Failures are loud + specific so a single `pytest` run flags
documentation drift the same way ruff flags code drift.

Compliance posture: reads only source/docs, never touches MIMIC.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from phantom_codes.cli import app

REPO_ROOT = Path(__file__).resolve().parents[1]

# Public-facing markdown docs that get reproducer/contributor eyeballs.
# CLAUDE.md / BACKLOG.md / NOTES.md are gitignored internal notes —
# excluded from the consistency check.
PUBLIC_DOCS = [
    REPO_ROOT / "README.md",
    REPO_ROOT / "BENCHMARK.md",
    REPO_ROOT / "paper" / "README.md",
    REPO_ROOT / "data" / "synthea" / "README.md",
]


def _registered_command_names() -> set[str]:
    """Pull command names from the typer app object."""
    names = set()
    for cmd in app.registered_commands:
        # typer's CommandInfo: name attribute may be None when relying on the function name
        names.add(cmd.name or cmd.callback.__name__.replace("_", "-"))
    return names


def _extract_phantom_codes_commands(text: str) -> set[str]:
    """Find every `phantom-codes <command>` invocation in markdown text.

    Handles both inline (`phantom-codes evaluate`) and code-block
    (```bash\\nphantom-codes evaluate ...```) forms via a single regex.
    """
    pattern = re.compile(r"phantom-codes\s+([a-z][a-z0-9-]+)")
    matches = pattern.findall(text)
    # Filter out `--help` and other typer-injected flags.
    return {m for m in matches if not m.startswith("-")}


def _extract_repo_relative_paths(text: str) -> set[str]:
    """Find candidate repo-relative paths mentioned in markdown.

    Looks at backtick-delimited paths that:
      - contain `/` (so we don't catch every backtick'd word)
      - don't start with `/` or `~` or `https?://`
      - end with a recognizable file extension OR are a known dir name

    This is intentionally conservative — false positives in this
    detector mean test churn; false negatives mean missed drift but
    no harm.
    """
    candidates = set()
    # Backtick-delimited paths. Filter to tokens that look like clean
    # file paths — single-line, no whitespace, no shell-syntax chars,
    # no command invocations.
    shell_chars = set(" \t\n|&;<>$()=\\")
    for m in re.finditer(r"`([^`]+)`", text):
        token = m.group(1)
        if not token or "/" not in token:
            continue
        if any(c in token for c in shell_chars):
            continue  # shell command, not a file path
        if token.startswith(("/", "~", "http://", "https://", "./")):
            # `./scripts/...` is technically valid but is more often a
            # shell invocation example than a doc reference. Strip the
            # leading `./` and re-evaluate.
            if token.startswith("./"):
                token = token[2:]
            else:
                continue
        # Strip line/column suffixes like `:42:5`
        token = re.sub(r":\d+(?::\d+)?$", "", token)
        # Strip glob characters
        token = token.split("*")[0].rstrip("/")
        if not token:
            continue
        candidates.add(token)

    # Markdown links: `[text](path)` where path doesn't start with http
    for m in re.finditer(r"\]\(([^)]+)\)", text):
        token = m.group(1).split("#")[0]  # strip anchors
        if not token or token.startswith(("http://", "https://", "mailto:")):
            continue
        if token.startswith(("/", "~")):
            continue
        # Strip glob, fragment
        token = token.split("*")[0].rstrip("/")
        if token:
            candidates.add(token)

    return candidates


# Files that get auto-generated and may not exist in a fresh clone but
# are intentionally referenced by docs (e.g., the eval CSV outputs,
# cohort artifacts that live behind .gitignore).
EXPECTED_RUNTIME_GENERATED = {
    "results/raw/headline_*.csv",  # generated by `evaluate`
    "results/summary/<run-id>",     # generated by `report`
    "models/checkpoints/pubmedbert/best_*.pt",  # generated by `train` (gitignored)
    "benchmarks/synthetic_v1/raw",
    "benchmarks/synthetic_v1/raw/fhir",
    "benchmarks/synthetic_v1/conditions.ndjson",
    "benchmarks/synthetic_v1/manifest.yaml",
    "tools/synthea",
    "tools/synthea/build/libs/synthea-with-dependencies.jar",
    "build/paper.pdf",  # paper build output
    "build/sections",
    "data/derived",  # MIMIC-derivative; gitignored
    "data/mimic",
    "data/mimic/raw",
}


# Path-tokens that look like file paths but aren't (config keys, syntax
# examples, etc.) — silence them rather than listing them as "missing."
NOT_ACTUALLY_PATHS = {
    # Config example values from BENCHMARK.md / README.md
    "sk-ant-",
    "sk-",
    "AIza",
    # Code/expression fragments that happen to contain `/`
}


@pytest.mark.parametrize("doc_path", PUBLIC_DOCS, ids=lambda p: p.name)
def test_doc_command_names_exist_in_cli(doc_path: Path) -> None:
    """Every `phantom-codes <command>` mentioned in docs must be a real CLI command."""
    if not doc_path.exists():
        pytest.skip(f"{doc_path} does not exist (yet)")

    text = doc_path.read_text()
    mentioned = _extract_phantom_codes_commands(text)
    registered = _registered_command_names()

    missing = mentioned - registered
    assert not missing, (
        f"{doc_path.relative_to(REPO_ROOT)} references CLI commands that don't "
        f"exist: {sorted(missing)}.\nRegistered commands: {sorted(registered)}"
    )


def _matches_runtime_generated(token: str) -> bool:
    """True if `token` is (or is a glob-stripped prefix of) any path in
    EXPECTED_RUNTIME_GENERATED. Allows `models/checkpoints/pubmedbert/best_`
    (after `*.pt` was stripped) to match the carve-out entry
    `models/checkpoints/pubmedbert/best_*.pt`."""
    if token in EXPECTED_RUNTIME_GENERATED:
        return True
    # Token might be a glob-stripped prefix (e.g., `best_` from `best_*.pt`)
    for entry in EXPECTED_RUNTIME_GENERATED:
        # Strip glob from the carve-out entry and compare
        stripped_entry = entry.split("*")[0].rstrip("/")
        if token == stripped_entry:
            return True
    return False


@pytest.mark.parametrize("doc_path", PUBLIC_DOCS, ids=lambda p: p.name)
def test_doc_file_paths_resolve(doc_path: Path) -> None:
    """Every project-relative file path in docs must exist on disk
    (with carve-outs for runtime-generated artifacts)."""
    if not doc_path.exists():
        pytest.skip(f"{doc_path} does not exist (yet)")

    text = doc_path.read_text()
    candidates = _extract_repo_relative_paths(text)

    missing = []
    # Resolve relative to the doc's directory so `../foo.md` in
    # paper/README.md resolves to repo-root/foo.md, not a missing
    # repo-root/../foo.md.
    doc_dir = doc_path.parent

    for token in sorted(candidates):
        if _matches_runtime_generated(token):
            continue
        if any(token.startswith(prefix) for prefix in NOT_ACTUALLY_PATHS):
            continue
        # Skip fragments that obviously aren't file references
        if token.startswith(("@", "<")):
            continue
        # Tokens with `=` aren't paths (they're CLI args)
        if "=" in token:
            continue
        # Skip pure namespace identifiers (e.g., `module.submodule`)
        if "." in token and "/" not in token:
            continue
        # Skip placeholder example paths (e.g., `../figures/foo.pdf` shown
        # only as a markdown-syntax example, not a real file reference).
        # Heuristic: the basename "foo" / "bar" / "baz" / "example" is
        # almost certainly a placeholder, not a real path.
        basename_stem = Path(token).stem.lower()
        if basename_stem in {"foo", "bar", "baz", "example"}:
            continue
        # Resolve relative to the doc's directory first; fall back to
        # repo root for ambiguous absolute-style references.
        candidate_path = (doc_dir / token).resolve()
        if not candidate_path.exists():
            # Try as repo-relative path too (some docs use that style)
            alt_path = REPO_ROOT / token
            if alt_path.exists():
                continue
            missing.append(token)

    assert not missing, (
        f"{doc_path.relative_to(REPO_ROOT)} references project paths that don't "
        f"exist:\n  " + "\n  ".join(missing)
        + "\n\nIf any of these are intentionally runtime-generated artifacts, "
        "add them to EXPECTED_RUNTIME_GENERATED in this file."
    )
